#!/usr/bin/env bash
set -euo pipefail

HYPRCTL="/usr/bin/hyprctl"

# Discover Hyprland signature if launched from Waybar/systemd
if [[ -z "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]]; then
  runtime="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
  if [[ -d "$runtime/hypr" ]]; then
    sig="$(ls -1t "$runtime/hypr" 2>/dev/null | head -n1 || true)"
    [[ -n "$sig" ]] && export HYPRLAND_INSTANCE_SIGNATURE="$sig"
  fi
fi

# Non-inheritable lock (won't get stuck due to fd inheritance)
LOCKDIR="${XDG_RUNTIME_DIR:-/tmp}/wallpaper.lockdir"
if ! mkdir "$LOCKDIR" 2>/dev/null; then
  echo "wallpaper.sh: already running (lock held), skipping."
  exit 0
fi
trap 'rmdir "$LOCKDIR" 2>/dev/null || true' EXIT INT TERM

WALLPAPER_DIR="$HOME/Pictures/Wallpapers"
HISTORY_FILE="$HOME/.cache/last_wallpaper_index"

WAYBAR_COLORS="$HOME/.config/waybar/colors.css"
KITTY_DYNAMIC="$HOME/.config/kitty/matugen.conf"

DUNST_RC="$HOME/.config/dunst/dunstrc"

BTOP_CONF="$HOME/.config/btop/btop.conf"
BTOP_THEME_DIR="$HOME/.config/btop/themes"
BTOP_THEME_FILE="$BTOP_THEME_DIR/matugen.theme"

# Pick next wallpaper
mapfile -t wallpapers < <(
  find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) | sort
)
((${#wallpapers[@]})) || { echo "No wallpapers found in $WALLPAPER_DIR"; exit 1; }

if [[ -f "$HISTORY_FILE" ]]; then
  last_index="$(cat "$HISTORY_FILE" 2>/dev/null || echo 0)"
  [[ "$last_index" =~ ^[0-9]+$ ]] || last_index=0
  index=$(( (last_index + 1) % ${#wallpapers[@]} ))
else
  index=0
fi

WALL="${wallpapers[$index]}"
echo "$index" > "$HISTORY_FILE"

echo "Setting wallpaper: $WALL"
timeout 5s awww img --transition-type random --transition-step 90 --transition-duration 1.2 --transition-fps 75 "$WALL" || true

# Generate colors (writes WAYBAR_COLORS via your matugen template)
timeout 30s matugen image "$WALL" --source-color-index 1 --quiet

[[ -f "$WAYBAR_COLORS" ]] || { echo "Missing $WAYBAR_COLORS"; exit 1; }


STARTPAGE_WALLCSS="$HOME/.local/share/startpage/wallpaper.css"
mkdir -p "$(dirname "$STARTPAGE_WALLCSS")"

# escape " and \ for CSS url("...")
wall_esc="${WALL//\\/\\\\}"
wall_esc="${wall_esc//\"/\\\"}"

cat > "$STARTPAGE_WALLCSS" <<EOF
:root { --wallpaper: url("file://${wall_esc}"); }
EOF



read_css_color() {
  local name="$1"
  awk -v n="$name" '
    $1=="@define-color" && $2==n {
      gsub(";", "", $3);
      print $3;
      exit
    }
  ' "$WAYBAR_COLORS"
}

# Colors used across everything
BACKGROUND="$(read_css_color background)"
ON_BACKGROUND="$(read_css_color on-background)"

SURFACE="$(read_css_color surface)"
ON_SURFACE="$(read_css_color on-surface)"

PRIMARY="$(read_css_color primary)"
SECONDARY="$(read_css_color secondary)"
TERTIARY="$(read_css_color tertiary)"

PRIMARY_CONTAINER="$(read_css_color primary-container)"
ON_PRIMARY_CONTAINER="$(read_css_color on-primary-container)"

OUTLINE="$(read_css_color outline)"
ERROR="$(read_css_color error)"
ON_PRIMARY="$(read_css_color on-primary)"

# Fallbacks
[[ -z "$SECONDARY" ]] && SECONDARY="$PRIMARY"
[[ -z "$TERTIARY" ]] && TERTIARY="$SECONDARY"
[[ -z "$ON_PRIMARY" ]] && ON_PRIMARY="#ffffff"
[[ -z "$ON_SURFACE" ]] && ON_SURFACE="$ON_BACKGROUND"
[[ -z "$PRIMARY_CONTAINER" ]] && PRIMARY_CONTAINER="$PRIMARY"
[[ -z "$ON_PRIMARY_CONTAINER" ]] && ON_PRIMARY_CONTAINER="$ON_PRIMARY"
[[ -z "$OUTLINE" ]] && OUTLINE="$SECONDARY"
[[ -z "$ERROR" ]] && ERROR="$PRIMARY"

if [[ -z "$PRIMARY" || -z "$SURFACE" ]]; then
  echo "Could not read primary/surface from $WAYBAR_COLORS"
  exit 1
fi

# --- Waybar reload (no respawn here) ---
# If you run waybar as a systemd user service, prefer that:
if systemctl --user --quiet is-active waybar.service 2>/dev/null; then
  systemctl --user kill -s SIGUSR2 waybar.service >/dev/null 2>&1 || true
else
  pkill -SIGUSR2 -x waybar >/dev/null 2>&1 || true
fi

# --- Kitty (non-live): write overrides (applies to new kitty windows / restart) ---
mkdir -p "$(dirname "$KITTY_DYNAMIC")"
cat > "$KITTY_DYNAMIC" <<EOF
# autogenerated by wallpaper.sh (matugen)
active_border_color     ${PRIMARY}
inactive_border_color   ${SURFACE}
active_tab_background   ${PRIMARY}
active_tab_foreground   ${ON_PRIMARY}
EOF

# --- Dunst adaptive: update a managed block and restart dunst ---
mkdir -p "$(dirname "$DUNST_RC")"
[[ -f "$DUNST_RC" ]] || printf "[global]\n" > "$DUNST_RC"

DUNST_START="# === MATUGEN DUNST START ==="
DUNST_END="# === MATUGEN DUNST END ==="

DUNST_BLOCK="$(cat <<EOF
$DUNST_START
[global]
frame_color = "${PRIMARY}"
separator_color = "${OUTLINE}"
highlight = "${PRIMARY}"
progress_bar = true
progress_bar_frame_width = 1
progress_bar_height = 8
progress_bar_frame_color = "${OUTLINE}"
progress_bar_min_width = 100
progress_bar_max_width = 300

[urgency_low]
background = "${SURFACE}"
foreground = "${ON_SURFACE}"
frame_color = "${OUTLINE}"

[urgency_normal]
background = "${SURFACE}"
foreground = "${ON_SURFACE}"
frame_color = "${PRIMARY}"

[urgency_critical]
background = "${ERROR}"
foreground = "${ON_PRIMARY}"
frame_color = "${ERROR}"
$DUNST_END
EOF
)"

tmp="$(mktemp)"
inblock=0
found=0
while IFS= read -r line || [[ -n "$line" ]]; do
  if [[ "$line" == "$DUNST_START" ]]; then
    inblock=1
    found=1
    printf "%s\n" "$DUNST_BLOCK" >> "$tmp"
    continue
  fi
  if (( inblock == 1 )); then
    [[ "$line" == "$DUNST_END" ]] && inblock=0
    continue
  fi
  printf "%s\n" "$line" >> "$tmp"
done < "$DUNST_RC"

if (( found == 0 )); then
  printf "\n%s\n" "$DUNST_BLOCK" >> "$tmp"
fi

cat "$tmp" > "$DUNST_RC"
rm -f "$tmp"

# Restart dunst so new colors apply immediately
pkill -x dunst >/dev/null 2>&1 || true
setsid -f dunst >/dev/null 2>&1 || true

# --- btop adaptive: write theme + set it in btop.conf (applies next btop start) ---
mkdir -p "$BTOP_THEME_DIR"
cat > "$BTOP_THEME_FILE" <<EOF
# autogenerated by wallpaper.sh (matugen)
theme[main_bg]="${BACKGROUND}"
theme[main_fg]="${ON_BACKGROUND}"
theme[title]="${PRIMARY}"
theme[hi_fg]="${PRIMARY}"
theme[selected_bg]="${PRIMARY_CONTAINER}"
theme[selected_fg]="${ON_PRIMARY_CONTAINER}"
theme[inactive_fg]="${OUTLINE}"
theme[graph_text]="${ON_BACKGROUND}"
theme[meter_bg]="${SURFACE}"
theme[proc_misc]="${SECONDARY}"

theme[cpu_start]="${PRIMARY}"
theme[cpu_mid]="${SECONDARY}"
theme[cpu_end]="${TERTIARY}"

theme[mem_start]="${SECONDARY}"
theme[mem_mid]="${TERTIARY}"
theme[mem_end]="${PRIMARY}"

theme[net_start]="${PRIMARY}"
theme[net_mid]="${SECONDARY}"
theme[net_end]="${TERTIARY}"

theme[warning]="${ERROR}"
theme[error]="${ERROR}"
EOF

mkdir -p "$(dirname "$BTOP_CONF")"
if [[ -f "$BTOP_CONF" ]]; then
  if grep -qE '^[[:space:]]*color_theme[[:space:]]*=' "$BTOP_CONF"; then
    sed -i 's/^[[:space:]]*color_theme[[:space:]]*=.*/color_theme = "matugen"/' "$BTOP_CONF"
  else
    printf '\ncolor_theme = "matugen"\n' >> "$BTOP_CONF"
  fi
else
  printf 'color_theme = "matugen"\n' > "$BTOP_CONF"
fi

# --- Hyprland borders via Lua eval ---
PRIMARY_HEX="${PRIMARY#\#}"
SECONDARY_HEX="${SECONDARY#\#}"
SURFACE_HEX="${SURFACE#\#}"

ACTIVE_1="rgba(${PRIMARY_HEX}ff)"
ACTIVE_2="rgba(${SECONDARY_HEX}ff)"
INACTIVE="rgba(${SURFACE_HEX}aa)"

LUA_CODE="$(printf 'hl.config({ general = { col = { active_border = { colors = { "%s", "%s" }, angle = 45 }, inactive_border = "%s" }}})' \
  "$ACTIVE_1" "$ACTIVE_2" "$INACTIVE")"

if [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]]; then
  "$HYPRCTL" eval "$LUA_CODE" >/dev/null
fi

echo "Done."
